### ISSUE TITLE
sigmausd.io shows wrong sigRSV balance 

### ISSUE THREAD

**Issue by AlexDochioiu** [anon-real/sigma-usd#13]
As the title says. My balance appearing in sigmausd website is about 4x the real held amount (as expected/as seen in yoroi).

**Comment by anon-real** [comment]
The balance in the header or down in the dashboard?

**Comment by AlexDochioiu** [comment]
Both of them. The sigRSV balance in the header is wrong. The equivalent value in dollars (in the dashboard) is based on the wrong sigRSV balance that appears in the header.

**Comment by AlexDochioiu** [comment]
If you give me an e-mail address, I'll send you the wallet address so you can debug it

**Comment by anon-real** [comment]
Thanks yes please send: anon_real_anon@protonmail.com

**Comment by anon-real** [comment]
Reported the issue to exlorer devs.
