### ISSUE TITLE
Texts don't load if not main page is loaded first

### ISSUE THREAD

**Issue by icza** [anon-real/sigma-usd#29]
I found an issue where not all texts are loaded / rendered if not the main page is loaded first.

For example if I load https://sigmausd.io/ in the browser and then navigate to the ReserveCoin page (https://sigmausd.io/#/reservecoin), all texts are loaded properly.

But if I'm on the ResrveCoin page and hit Refresh in the browser, the `"Provide liquidity and earn premiums upon redemption"` text disappears and only `reserveTag` is displayed in its place. This is just one example.

I am using Chrome Version 90.0.4430.212 (Official Build) (64-bit), on Ubuntu 20.04.02 LTS.

Opening the developer console, I can see the following JavaScript warnings:

```
2.15f9c5fc.chunk.js:1 i18next: hasLoadedNamespace: i18next was not initialized undefined

2.15f9c5fc.chunk.js:1 i18next::translator: key "menuDash" for languages "en" won't get resolved as namespace "translation" was not yet loaded This means something IS WRONG in your setup. You access the t function before i18next.init / i18next.loadNamespace / i18next.changeLanguage was done. Wait for the callback or Promise to resolve before accessing it!!!

2.15f9c5fc.chunk.js:1 i18next::backendConnector: loading namespace translation for language en-US failed failed parsing /locales/en-US/translation.json to json
```

**Comment by icza** [comment]
I would also like to note that visiting https://sigmausd.io/ from my mobile (Android, Chrome browser) I also experience several text / translation issues too, regardless of which page I start from.

**Comment by anon-real** [comment]
@deadit I confirm this issue, please take a look.
