### ISSUE TITLE
How to release pending transactions?

### ISSUE THREAD

**Issue by chriswill** [anon-real/sigma-usd#57]
![image](https://user-images.githubusercontent.com/216290/132955490-867dc701-b33d-4bf7-8e32-2ebfd42110a5.png)

The bottom transaction is shown as pending for the last 12 hours.  It has a transaction ID, but it shows as Not Found in Ergo Explorer.

The weird part is that I sent the funds from Yoroi, and they've left my wallet, but I don't have a transaction shown there that I can pull a destination address from to use the "Refund" feature.  It seems like there was some glitch in the SC that invalidated the incoming transaction and locked the funds.

**Comment by anon-real** [comment]
Use the tx that you've sent with Yoroi to find the address you've sent to. Then use the refund feature.

**Comment by chriswill** [comment]
Thanks.  I've since gone thru my wallet transactions and my balance is as expected.  So I'm not missing funds.  The UI is an error artifact somehow, but no refund is required/expected.
